export const WORKSPACE_LIBRARY = {
  core: {
    id: "core",
    name: "Core",
    purpose: "Personal operating system, goals, priorities, decisions, time planning.",
    tasks: "prioritization, planning, decision support, goals, routines",
    risk: "Medium",
    approvals: "outside-world actions, financial decisions, irreversible changes",
  },
  business: {
    id: "business",
    name: "Business",
    purpose: "Company, clients, proposals, strategy, sales, operations.",
    tasks: "proposals, client communication, strategy, marketing, sales, operations",
    risk: "Medium",
    approvals: "client delivery, publishing, pricing, external saves, public messages",
  },
  coding: {
    id: "coding",
    name: "Coding",
    purpose: "Software, debugging, repos, agents, automations, deployment.",
    tasks: "debugging, MVP builds, repo inspection, tests, deployment, automations",
    risk: "High",
    approvals: "file edits, destructive commands, production changes, database resets, deployments",
  },
  design: {
    id: "design",
    name: "Design",
    purpose: "UX, UI, interaction design, product flows, design systems, critique.",
    tasks: "UX audit, UI critique, design systems, product flows, wireframes, microcopy",
    risk: "Low",
    approvals: "publishing externally, client delivery, live product changes",
  },
  education: {
    id: "education",
    name: "Education",
    purpose: "Teaching, curriculum, workshops, assignments, student feedback.",
    tasks: "curriculum, lesson plans, assignments, critique, workshops, student feedback",
    risk: "Low",
    approvals: "publishing curriculum, sending to students, public announcements",
  },
  admin: {
    id: "admin",
    name: "Admin",
    purpose: "Emails, documents, forms, banking, insurance, official communication.",
    tasks: "emails, forms, document review, applications, banking, insurance, official letters",
    risk: "High",
    approvals: "sending, submitting, signing, uploading, legal claims, financial decisions",
  },
  academics: {
    id: "academics",
    name: "Academics",
    purpose: "Exams, reports, research, notes, papers, assignments.",
    tasks: "exam prep, notes, reports, research, numericals, syllabus analysis, paper review",
    risk: "Low",
    approvals: "final submission, uploading to institution, public sharing",
  },
  creative: {
    id: "creative",
    name: "Creative",
    purpose: "Prompts, posters, campaigns, art direction, lyrics, visual concepts.",
    tasks: "image prompts, poster concepts, moodboards, campaigns, creative writing, lyrics",
    risk: "Low",
    approvals: "publishing externally, sending to clients, paid generation tools",
  },
  finance: {
    id: "finance",
    name: "Finance",
    purpose: "Budgets, invoices, spending decisions, pricing, financial planning.",
    tasks: "budgeting, pricing, invoices, payment tracking, expense review, financial planning",
    risk: "High",
    approvals: "payments, purchases, bank actions, financial commitments, tax/legal claims",
  },
  research: {
    id: "research",
    name: "Research",
    purpose: "Knowledge synthesis, market scans, reports, evidence gathering.",
    tasks: "research synthesis, market scans, notes, reports, source comparison, summaries",
    risk: "Medium",
    approvals: "public claims, client-facing reports, medical/legal/financial advice",
  },
};
