// Exhaustive option sets per workspace type.
// Key = slugified workspace name. "custom" is the fallback for names with no match.

export const RISK_OPTIONS = [
  { value: "Low", description: "Mostly drafting and review. Few outside effects." },
  { value: "Medium", description: "Some outside effects. Real consequences if rushed." },
  { value: "High", description: "Money, production systems, legal, or hard-to-undo." },
];

export const WORKSPACE_OPTIONS = {
  core: {
    label: "Core (personal OS)",
    suggestedRisk: "Medium",
    purpose: [
      "Personal operating system",
      "Goals and priorities",
      "Daily and weekly planning",
      "Decision support",
      "Habits and routines",
      "Journaling and reflection",
      "Time and energy management",
      "Life admin",
    ],
    tasks: [
      "prioritization",
      "planning",
      "decision support",
      "goal setting",
      "routines",
      "journaling",
      "weekly review",
      "time blocking",
      "energy management",
      "habit tracking",
    ],
    approvals: [
      "outside-world actions",
      "financial decisions",
      "irreversible changes",
      "sending messages to others",
      "public commitments",
      "calendar invites",
    ],
  },
  business: {
    label: "Business",
    suggestedRisk: "Medium",
    purpose: [
      "Company and clients",
      "Proposals and pitches",
      "Strategy",
      "Sales outreach",
      "Marketing",
      "Operations",
      "Partnerships",
      "Pricing",
    ],
    tasks: [
      "proposals",
      "client communication",
      "strategy",
      "marketing",
      "sales",
      "operations",
      "contracts",
      "partnership outreach",
      "market positioning",
      "competitor scans",
    ],
    approvals: [
      "client delivery",
      "publishing externally",
      "pricing changes",
      "external saves",
      "public messages",
      "signing contracts",
      "sending to leads",
    ],
  },
  coding: {
    label: "Coding",
    suggestedRisk: "High",
    purpose: [
      "Software development",
      "Debugging",
      "Repo management",
      "Automation",
      "Deployment",
      "Testing",
      "Refactoring",
      "Code review",
    ],
    tasks: [
      "debugging",
      "MVP builds",
      "repo inspection",
      "tests",
      "deployment",
      "automations",
      "refactoring",
      "code review",
      "architecture planning",
      "CI/CD setup",
      "dependency upgrades",
    ],
    approvals: [
      "file edits",
      "destructive commands",
      "production changes",
      "database resets",
      "deployments",
      "dependency upgrades",
      "secrets or env changes",
      "force pushes",
      "schema migrations",
    ],
  },
  design: {
    label: "Design",
    suggestedRisk: "Low",
    purpose: [
      "UX research",
      "UI critique",
      "Design systems",
      "Product flows",
      "Wireframing",
      "Prototyping",
      "Microcopy",
      "Accessibility",
    ],
    tasks: [
      "UX audit",
      "UI critique",
      "design systems",
      "product flows",
      "wireframes",
      "microcopy",
      "accessibility review",
      "prototype review",
      "heuristic evaluation",
      "moodboards",
    ],
    approvals: [
      "publishing externally",
      "client delivery",
      "live product changes",
      "public design uploads",
      "design-system changes",
    ],
  },
  education: {
    label: "Education",
    suggestedRisk: "Low",
    purpose: [
      "Curriculum design",
      "Lesson planning",
      "Workshop design",
      "Student feedback",
      "Assessment",
      "Syllabus",
    ],
    tasks: [
      "curriculum",
      "lesson plans",
      "assignments",
      "critique",
      "workshops",
      "student feedback",
      "rubrics",
      "grading help",
      "syllabus drafts",
    ],
    approvals: [
      "publishing curriculum",
      "sending to students",
      "public announcements",
      "grade submissions",
      "parent communication",
    ],
  },
  admin: {
    label: "Admin",
    suggestedRisk: "High",
    purpose: [
      "Email handling",
      "Document review",
      "Forms",
      "Banking",
      "Insurance",
      "Official communication",
      "Compliance",
    ],
    tasks: [
      "emails",
      "forms",
      "document review",
      "applications",
      "banking",
      "insurance",
      "official letters",
      "scheduling",
      "record-keeping",
    ],
    approvals: [
      "sending",
      "submitting",
      "signing",
      "uploading",
      "legal claims",
      "financial decisions",
      "official replies",
    ],
  },
  academics: {
    label: "Academics",
    suggestedRisk: "Low",
    purpose: [
      "Exam preparation",
      "Research notes",
      "Paper writing",
      "Syllabus analysis",
      "Reports",
      "Study planning",
    ],
    tasks: [
      "exam prep",
      "notes",
      "reports",
      "research",
      "numericals",
      "syllabus analysis",
      "paper review",
      "citation help",
      "literature review",
    ],
    approvals: [
      "final submission",
      "uploading to institution",
      "public sharing",
      "co-author sign-off",
      "plagiarism-sensitive work",
    ],
  },
  creative: {
    label: "Creative",
    suggestedRisk: "Low",
    purpose: [
      "Image and visual concepting",
      "Campaign ideation",
      "Art direction",
      "Creative writing",
      "Brand voice",
    ],
    tasks: [
      "image prompts",
      "poster concepts",
      "moodboards",
      "campaigns",
      "creative writing",
      "lyrics",
      "taglines",
      "brand voice",
      "brainstorms",
    ],
    approvals: [
      "publishing externally",
      "sending to clients",
      "paid generation tools",
      "brand-impacting choices",
      "public posts",
    ],
  },
  finance: {
    label: "Finance",
    suggestedRisk: "High",
    purpose: [
      "Budgeting",
      "Invoicing",
      "Pricing",
      "Expense review",
      "Financial planning",
      "Cashflow",
      "Tax prep",
    ],
    tasks: [
      "budgeting",
      "pricing",
      "invoices",
      "payment tracking",
      "expense review",
      "financial planning",
      "cashflow analysis",
      "tax prep",
      "runway modeling",
    ],
    approvals: [
      "payments",
      "purchases",
      "bank actions",
      "financial commitments",
      "tax or legal claims",
      "contract signing",
    ],
  },
  research: {
    label: "Research",
    suggestedRisk: "Medium",
    purpose: [
      "Knowledge synthesis",
      "Market scans",
      "Evidence gathering",
      "Source comparison",
      "Literature review",
    ],
    tasks: [
      "research synthesis",
      "market scans",
      "notes",
      "reports",
      "source comparison",
      "summaries",
      "fact-checking",
      "citation mapping",
      "literature reviews",
    ],
    approvals: [
      "public claims",
      "client-facing reports",
      "medical, legal, or financial advice",
      "citations in published work",
    ],
  },
  custom: {
    label: "Custom",
    suggestedRisk: "Medium",
    purpose: [
      "Planning",
      "Drafting",
      "Analysis",
      "Communication",
      "Decision support",
      "Execution",
      "Review and critique",
      "Research and synthesis",
      "Automation",
    ],
    tasks: [
      "planning",
      "prioritization",
      "drafting",
      "reviewing",
      "summarizing",
      "brainstorming",
      "research",
      "decision support",
      "writing",
      "analysis",
    ],
    approvals: [
      "sending messages",
      "publishing content",
      "making purchases",
      "deleting files",
      "submitting forms",
      "uploading documents",
      "financial decisions",
      "editing production systems",
      "irreversible changes",
      "client-facing work",
      "public sharing",
    ],
  },
};

export function getOptionsForWorkspace(slug) {
  return WORKSPACE_OPTIONS[slug] || WORKSPACE_OPTIONS.custom;
}
